export interface Order {
	name: string;
	owner: string;
	creation: string;
	modified: string;
	modified_by: string;
	docstatus: number;
	idx: number;
	first_name: string;
	middle_name: string;
	last_name: string;
	email: string;
	phone: string;
	street_name: string;
	street_number: string;
	postal_code: string;
	city: string;
	country: string;
	notes: string;
	shipping: string;
	shipment_tracking_code: string;
	payment_id: string;
	doctype: string;
	items: {
		name: string
		owner: string
		creation: string
		modified: string
		modified_by: string
		docstatus: number
		idx: number
		item_code: string
		schedule_date: string
		image: string
		qty: number
		stock_uom: string
		uom: string
		conversion_factor: number
		stock_qty: number
		min_order_qty: number
		projected_qty: number
		actual_qty: number
		ordered_qty: number
		received_qty: number
		rate: number
		price_list_rate: number
		amount: number
		page_break: number
		parent: string
		parentfield: string
		parenttype: string
		doctype: string
	}[];
}